import { User, Ticket, Message, Review, BlogPost } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Admin User',
    email: 'admin@ticketsystem.com',
    role: 'admin',
    bio: 'System administrator',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    name: 'Sarah Johnson',
    email: 'sarah@ticketsystem.com',
    role: 'support_agent',
    bio: 'Senior support specialist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user-3',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'customer',
    bio: 'Product enthusiast',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'user-4',
    name: 'Mike Wilson',
    email: 'mike@ticketsystem.com',
    role: 'support_agent',
    bio: 'Technical support expert',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mike',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'user-5',
    name: 'Emily Davis',
    email: 'emily@example.com',
    role: 'customer',
    bio: 'Marketing professional',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    createdAt: new Date('2024-02-15'),
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 'ticket-1',
    title: 'Cannot access my account',
    description: 'I have been trying to log in for the past hour but keep getting an error message.',
    status: 'in-progress',
    priority: 'high',
    customerId: 'user-3',
    assignedAgentId: 'user-2',
    createdAt: new Date('2024-03-01T10:30:00'),
    updatedAt: new Date('2024-03-01T14:20:00'),
  },
  {
    id: 'ticket-2',
    title: 'Payment not processing',
    description: 'My payment has been declined multiple times even though I have sufficient funds.',
    status: 'open',
    priority: 'urgent',
    customerId: 'user-5',
    createdAt: new Date('2024-03-02T09:15:00'),
    updatedAt: new Date('2024-03-02T09:15:00'),
  },
  {
    id: 'ticket-3',
    title: 'Feature request: Dark mode',
    description: 'Would love to see a dark mode option in the application.',
    status: 'resolved',
    priority: 'low',
    customerId: 'user-3',
    assignedAgentId: 'user-4',
    createdAt: new Date('2024-02-20T16:00:00'),
    updatedAt: new Date('2024-02-28T11:30:00'),
    resolvedAt: new Date('2024-02-28T11:30:00'),
  },
  {
    id: 'ticket-4',
    title: 'Email notifications not working',
    description: 'I am not receiving any email notifications for my account activities.',
    status: 'in-progress',
    priority: 'medium',
    customerId: 'user-5',
    assignedAgentId: 'user-2',
    createdAt: new Date('2024-02-28T13:45:00'),
    updatedAt: new Date('2024-03-01T10:00:00'),
  },
  {
    id: 'ticket-5',
    title: 'Mobile app crashing',
    description: 'The mobile app crashes every time I try to upload a file.',
    status: 'closed',
    priority: 'high',
    customerId: 'user-3',
    assignedAgentId: 'user-4',
    createdAt: new Date('2024-02-15T08:20:00'),
    updatedAt: new Date('2024-02-25T15:30:00'),
    resolvedAt: new Date('2024-02-25T15:30:00'),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    ticketId: 'ticket-1',
    senderId: 'user-3',
    content: 'I have been trying to log in for the past hour but keep getting an error message.',
    createdAt: new Date('2024-03-01T10:30:00'),
  },
  {
    id: 'msg-2',
    ticketId: 'ticket-1',
    senderId: 'user-2',
    content: 'Hi John, I understand your concern. Can you please tell me what error message you are seeing?',
    createdAt: new Date('2024-03-01T11:15:00'),
  },
  {
    id: 'msg-3',
    ticketId: 'ticket-1',
    senderId: 'user-3',
    content: 'It says "Invalid credentials" even though I am sure my password is correct.',
    createdAt: new Date('2024-03-01T11:20:00'),
  },
  {
    id: 'msg-4',
    ticketId: 'ticket-1',
    senderId: 'user-2',
    content: 'Let me reset your password for you. Please check your email in a few minutes.',
    createdAt: new Date('2024-03-01T14:20:00'),
  },
  {
    id: 'msg-5',
    ticketId: 'ticket-3',
    senderId: 'user-3',
    content: 'Would love to see a dark mode option in the application.',
    createdAt: new Date('2024-02-20T16:00:00'),
  },
  {
    id: 'msg-6',
    ticketId: 'ticket-3',
    senderId: 'user-4',
    content: 'Thank you for your suggestion! We have added dark mode to our roadmap.',
    createdAt: new Date('2024-02-28T11:30:00'),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    ticketId: 'ticket-3',
    customerId: 'user-3',
    rating: 5,
    comment: 'Great support! Very responsive and helpful.',
    createdAt: new Date('2024-02-28T12:00:00'),
  },
  {
    id: 'review-2',
    ticketId: 'ticket-5',
    customerId: 'user-3',
    rating: 4,
    comment: 'Issue was resolved quickly. Happy with the service.',
    createdAt: new Date('2024-02-25T16:00:00'),
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'post-1',
    title: 'How to Get the Most Out of Our Support System',
    content: 'Our ticketing system is designed to provide you with the best support experience. Here are some tips on how to create effective support tickets...',
    excerpt: 'Learn how to create effective support tickets and get faster resolutions.',
    authorId: 'user-1',
    category: 'Tips & Tricks',
    tags: ['support', 'guide', 'best-practices'],
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'post-2',
    title: 'New Features Released: February 2024',
    content: 'We are excited to announce several new features that will enhance your experience with our platform...',
    excerpt: 'Check out the latest features and improvements we have released this month.',
    authorId: 'user-1',
    category: 'Product Updates',
    tags: ['features', 'updates', 'announcements'],
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'post-3',
    title: 'Understanding Priority Levels',
    content: 'When creating a support ticket, choosing the right priority level helps us serve you better...',
    excerpt: 'A guide to selecting the appropriate priority level for your support tickets.',
    authorId: 'user-2',
    category: 'Support',
    tags: ['support', 'priorities', 'guide'],
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'post-4',
    title: 'Meet Our Support Team',
    content: 'Get to know the dedicated professionals who are here to help you 24/7...',
    excerpt: 'Introducing the team behind our world-class customer support.',
    authorId: 'user-1',
    category: 'Company',
    tags: ['team', 'about', 'support'],
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];
